language: node_js
os: osx
node_js:
  - "8.9.4"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test
  - CI=false yarn build --publish=never
deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: false